SELECT USERID
, NICKNAME
, CITY||' '||STREETADDRESS1||' '||STREETADDRESS2 AS 전체주소
, SUBSTR(TLNO,1,3)||'-'||SUBSTR(TLNO,4,4)||'-'||SUBSTR(TLNO,8) AS 전화번호
FROM USEDGOODSUSER
WHERE USERID IN (SELECT WRITERID
FROM USEDGOODSBOARD
GROUP BY WRITERID
HAVING COUNT(TITLE) >=3)
ORDER BY USER_ID DESC