-- 코드를 작성해주세요

SELECT   COUNT(*) AS FISH_COUNT, MIN(FISH_NAME) AS FISH_NAME
FROM    (SELECT   F.FISH_TYPE, I.FISH_NAME 
         FROM     FISH_INFO F,
                  FISH_NAME_INFO I
         WHERE    F.FISH_TYPE = I.FISH_TYPE) FF
GROUP BY FISH_TYPE
ORDER BY FISH_COUNT DESC;