-- 코드를 작성해주세요

SELECT   YEAR(DIFFERENTIATION_DATE) YEAR,
         MAX - SIZE_OF_COLONY YEAR_DEV,
         ID
FROM     ECOLI_DATA E,
        (SELECT   MAX(SIZE_OF_COLONY) MAX, 
                  YEAR(DIFFERENTIATION_DATE) YEAR
         FROM     ECOLI_DATA
         GROUP BY YEAR(DIFFERENTIATION_DATE)) A
WHERE    YEAR(E.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY YEAR, YEAR_DEV
