-- 코드를 입력하세요
SELECT B.CATEGORY AS CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS, BOOK B
WHERE BS.BOOK_ID = B.BOOK_ID
AND TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;